'use client';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Choice } from './layout-settings';
import { type Layout } from '@/lib/layouts';
import { applyReference, builtinBk, builtinReferences, criteriaOptions, matchReference, referenceSchema, type Reference } from '@/lib/criteria';
import { importReferenceRows, MAX_REFERENCE_BYTES, type ReferenceImportMode } from '@/lib/reference-import';
import type { Paper } from '@/lib/papers';

function rDescription(reference:Reference) {return builtinReferences.some(r=>r.id===reference.id)?'Clarivate 또는 출판사 공식 자료에서 SCIE 수록을 확인한 일부 목록입니다. 현재 수록 상태이며 과거 수록기간을 뜻하지 않습니다.':'사용자가 가져온 기준표입니다. 최신판과 인정 범위를 출처에서 확인하세요.';}
export function CriteriaPanel({layout,onLayout,papers,onApply}:{layout:Layout;onLayout:(v:Layout)=>void;papers:Paper[];onApply:(values:Paper[])=>void}) {
  const [open,setOpen]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [checked,setChecked]=useState<Set<string>>(new Set());const [overrides,setOverrides]=useState<Record<string,string>>({});const [page,setPage]=useState(0);const [find,setFind]=useState('');
  const [name,setName]=useState('');const [year,setYear]=useState(String(new Date().getFullYear()));const [url,setUrl]=useState('');const [paste,setPaste]=useState('');
  const [importMode,setImportMode]=useState<ReferenceImportMode>('mixed');
  const references=[...builtinReferences,...layout.criteria.custom];const reference=references.find(r=>r.id===layout.criteria.selected);
  const options=[...criteriaOptions,...layout.criteria.custom.map(r=>({key:r.id,label:r.name+' ('+r.year+')'}))];
  const candidates=reference?papers.map(p=>{const matches=matchReference(p,reference);const row=overrides[p.id]!==undefined?reference.rows[Number(overrides[p.id])]:matches.length===1?matches[0]:undefined;return{paper:p,row,ambiguous:matches.length>1};}):[];
  const rowOptions=reference?[{key:'none',label:'미확인 / 기준표에서 직접 선택'},...reference.rows.map((r,i)=>({key:String(i),label:(r.alias?r.alias+' · ':'')+r.venue+' · '+r.issn})).filter(r=>!find||r.label.toLowerCase().includes(find.toLowerCase())).slice(0,100)]:[];
  function reset() {setChecked(new Set());setOverrides({});setPage(0);setError('');setMessage('');setFind('');}
  function addReference() {try {
    if(layout.criteria.custom.length>=10)throw new Error('추가 기준표는 10개까지입니다. 프리셋을 나누어 저장하세요.');
    const {rows,skipped,duplicates}=importReferenceRows(paste,importMode);
    const parsed=referenceSchema.safeParse({id:crypto.randomUUID(),name,year,url,rows});if(!parsed.success)throw new Error('기준표 이름·연도·http(s) 출처와 각 행을 확인하세요. 구분은 SCIE, BK인정, CS우수학술대회, h5-index, 참고 중 하나이며, h5 값은 정수입니다.');
    onLayout({...layout,criteria:{...layout.criteria,selected:parsed.data.id,custom:[...layout.criteria.custom,parsed.data],automaticSources:[...layout.criteria.automaticSources,parsed.data.id]}});reset();setMessage(parsed.data.rows.length+'개 항목의 기준표를 추가했습니다. '+(skipped?`SCIE가 명시되지 않은 ${skipped}행 제외. `:'')+(duplicates?`같은 행 ${duplicates}개 정리. `:'')+'양식·프리셋 저장으로 보관하세요.');
  } catch(e){setError((e as Error).message);} }
  function apply() {if(!reference)return;const changes=candidates.filter(c=>c.row&&checked.has(c.paper.id)&&c.row.category!=='참고').map(c=>applyReference(c.paper,reference,c.row!));onApply(changes);setMessage(changes.length+'건에 구분·근거를 반영했습니다. 기존 IF는 유지하고 빈 IF만 보완했습니다.');setChecked(new Set());}
  const sourceInfo:Record<string,{url:string;description:string}>={
    'kiise-2024':{url:'https://aisociety.kr/sub/sub_04_02.php',description:'공식 안내에 게시된 최신 개편 목록은 2024판(216개)입니다. 2026-05-22 학회 공지는 연구재단 인정 논의 중임을 설명합니다. BK 목록과 별개입니다. 참고용 권장 목록이며 BK 인정 자동 판정과 일괄 반영에 사용하지 않습니다.'},
    'scie-live':{url:'https://mjl.clarivate.com/',description:'ISSN으로 학술지를 찾고 Science Citation Index Expanded 수록 여부와 수록기간을 확인하세요. 전체 색인 목록 다운로드는 현재 Web of Science 구독이 필요합니다. 현재 수록 상태와 논문 출판 당시 수록 여부는 다를 수 있습니다. IF만으로 SCIE 여부를 판정하지 않습니다.'},
    'h5-cs-2025':{url:'https://scholar.google.com/citations?view_op=top_venues&hl=ko&vq=eng',description:'Google 공식 안내 기준 2025년 7월판입니다(2020–2024 발행 논문). Engineering & Computer Science에서 세부 CS 분야를 선택하세요. 학술지·학술대회 지표이며 저자 h-index와 다릅니다.'},
    'h5-all-2025':{url:'https://scholar.google.com/citations?view_op=top_venues&hl=ko',description:'Google 공식 안내 기준 2025년 7월판입니다. 언어·분야를 변경하거나 학술지명으로 검색하세요. 미수록은 h5-index 50 미만을 뜻하지 않습니다.'},
  }; const external=sourceInfo[layout.criteria.selected];
  return <><Button variant="outline" onClick={()=>{reset();setOpen(true);}}>인정 기준·자료 선택</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="layout-dialog"><DialogHeader><DialogTitle>인정 기준 확인 · CS 우선</DialogTitle><DialogDescription>SCIE / CS우수학술대회 / h5-index 50 이상 학술대회를 구분에 자동 입력합니다. 자료 조사일: 2026-09-16. 직접 입력한 값은 유지합니다.</DialogDescription></DialogHeader>
    <div className="reference-info"><label className="preset-actions"><Checkbox aria-label="인정 구분 자동 입력" checked={layout.criteria.automatic} onCheckedChange={v=>onLayout({...layout,criteria:{...layout.criteria,automatic:v===true}})}/><strong>인정 구분 자동 입력</strong></label><p>아래 사용 중인 기준표를 논문 조회·출판정보 보완 때 자동 대조합니다. 일치 근거와 기준연도도 기록하며, 화면·Excel·CSV에 같은 구분을 적용합니다. 미일치는 미확인입니다.</p><p><strong>BK 판정에 학회 권장 목록을 사용하지 않습니다.</strong> SCIE는 IEEE 167개·출판사 확인 3개·Clarivate 개별 확인 5개를 내장합니다. 전체 목록은 아니며, 기준표에서 찾지 못해도 SCIE 비해당을 뜻하지 않습니다. h5는 확인한 기준표를 추가해야 자동 입력할 수 있습니다. 학술대회 h5가 50 이상일 때만 해당 구분을 채웁니다.</p><details><summary>자동 대조에 사용할 자료 선택</summary>{references.map(r=><label className="preset-actions" key={r.id}><Checkbox aria-label={r.name+' 자동 대조'} checked={layout.criteria.automaticSources.includes(r.id)} onCheckedChange={v=>onLayout({...layout,criteria:{...layout.criteria,automaticSources:v===true?[...new Set([...layout.criteria.automaticSources,r.id])]:layout.criteria.automaticSources.filter(id=>id!==r.id)}})}/><span>{r.name} · {r.rows.length}개</span></label>)}</details><small>학술대회 발표 트랙·워크숍·기관 적용 범위는 별도 확인하세요. 자동 일치는 ‘직접 확인 완료’가 아닙니다. 설정은 양식·프리셋에 저장됩니다.</small></div>
    <Choice label="원문 확인·수동 검토할 기준 자료" value={layout.criteria.selected} options={options} onChange={selected=>{onLayout({...layout,criteria:{...layout.criteria,selected}});reset();}}/>
    {external&&<div className="reference-info"><p>{external.description}</p><a href={external.url} target="_blank" rel="noopener noreferrer">선택한 공식 자료 열기 ↗</a><p>이 외부 자료는 실시간으로 수집하지 않습니다. 확인한 SCIE/h5 기준표를 아래에 가져오면 자동 대조할 수 있습니다. 한국정보과학회 권장 목록은 BK 근거로 사용하지 마세요.</p></div>}
    {reference&&<><div className="reference-info"><strong>{reference.name} · {reference.rows.length}개</strong><p>{reference.id===builtinBk.id?'2026-03-23 대한민국과학상·공학상 공고에 첨부된 BK 목록을 수록했습니다. 공고 연도 2026은 목록이 2026년에 개정되었다는 뜻이 아닙니다.':rDescription(reference)}</p><a href={reference.url} target="_blank" rel="noopener noreferrer">기준표 출처 ↗</a><p>ISSN 또는 연도·회차·문장부호를 정리한 학술지명/약칭이 같을 때만 후보로 표시합니다. 일치하지 않으면 미확인입니다. 학술대회 발표 트랙·워크숍과 기관 적용 여부를 검토한 행만 체크하세요.</p></div>
    <div className="preset-actions"><strong>표시·선택된 논문 {papers.length}건 중 후보 {candidates.filter(c=>c.row).length}건</strong><Input aria-label="수동 선택용 기준표 검색" placeholder="직접 선택 검색 (최대 100개): 학술지명·ISSN" value={find} onChange={e=>setFind(e.target.value)}/></div>
    <div className="criteria-table"><Table><TableHeader><TableRow><TableHead>검토</TableHead><TableHead>논문 / 검색된 출처</TableHead><TableHead>기준표 항목 (직접 변경 가능)</TableHead><TableHead>기록할 값</TableHead></TableRow></TableHeader><TableBody>{candidates.slice(page*50,page*50+50).map(c=><TableRow key={c.paper.id}><TableCell><Checkbox disabled={!c.row||c.row.category==='참고'} checked={checked.has(c.paper.id)} aria-label={c.paper.values.title+' 기준 검토 완료'} onCheckedChange={v=>setChecked(prev=>{const next=new Set(prev);v===true?next.add(c.paper.id):next.delete(c.paper.id);return next;})}/></TableCell><TableCell><strong>{c.paper.values.title}</strong><p>{c.paper.values.venue||'학술지·학술대회명 없음'} · {c.paper.values.issn}</p>{c.ambiguous&&<small>여러 후보가 있어 직접 선택해야 합니다.</small>}</TableCell><TableCell><Choice label={c.paper.values.title+' 기준표 매칭'} value={c.row?String(reference.rows.indexOf(c.row!)):'none'} options={c.row&&!rowOptions.some(o=>o.key===String(reference.rows.indexOf(c.row!)))?[...rowOptions,{key:String(reference.rows.indexOf(c.row!)),label:c.row.venue}]:rowOptions} onChange={v=>{setOverrides({...overrides,[c.paper.id]:v==='none'?'-1':v});setChecked(prev=>{const next=new Set(prev);next.delete(c.paper.id);return next;});}}/></TableCell><TableCell>{c.row?c.row.category+(c.row.category==='h5-index'?' '+c.row.value:'')+(c.row.impactFactor?' · 인정 IF '+c.row.impactFactor:''):'미확인'}</TableCell></TableRow>)}</TableBody></Table></div>
    {!papers.length&&<p className="field-hint">논문을 조회하고 행을 선택하면 기준표와 대조합니다.</p>}<div className="preset-actions"><Button variant="outline" disabled={!page} onClick={()=>setPage(page-1)}>이전 50건</Button><span>{page+1} / {Math.max(1,Math.ceil(candidates.length/50))}</span><Button variant="outline" disabled={(page+1)*50>=candidates.length} onClick={()=>setPage(page+1)}>다음 50건</Button><Button disabled={!checked.size} onClick={apply}>검토한 {checked.size}건 반영</Button></div></>}
    <details className="header-import"><summary>기준표 추가 · CSV 파일 / Excel 붙여넣기</summary>
      <p>학술지명(Journal Title), ISSN, eISSN을 인식합니다. Index / Web of Science Index 열이 있으면 SCIE가 명시된 행만 가져옵니다. SSCI·ESCI나 IF만으로 SCIE를 판정하지 않습니다. 최대 30,000행·10MB입니다.</p>
      <Choice label="가져올 기준표 형식" value={importMode} options={[{key:'mixed',label:'구분 또는 Index 열이 있는 기준표'},{key:'scie',label:'SCIE 전용 목록 (출처에서 SCIE만 담긴 목록임을 확인)'}]} onChange={v=>setImportMode(v as ReferenceImportMode)}/>
      <p>SCIE 전용 목록에는 구분 열이 없어도 됩니다. 다른 기준표는 학술지명 / ISSN / 약칭 / 구분 / 값 / 인정 IF 머리글을 사용하세요. 구분: SCIE / BK인정 / CS우수학술대회 / h5-index / 참고. h5는 값 열에 학술대회 지표를 넣으세요.</p>
      <div className="reference-form"><Input aria-label="기준표 이름" placeholder="기준표 이름 / 분야" value={name} onChange={e=>setName(e.target.value)} maxLength={100}/><Input aria-label="기준표 연도" placeholder="자료 기준연도" value={year} onChange={e=>setYear(e.target.value)} maxLength={4}/><Input aria-label="기준표 출처" placeholder="공식 출처 URL" value={url} onChange={e=>setUrl(e.target.value)}/></div>
      <label>CSV / TSV 파일<input type="file" accept=".csv,.tsv,.txt" onChange={async e=>{const input=e.currentTarget;const file=input.files?.[0];if(!file)return;try{if(file.size>MAX_REFERENCE_BYTES)throw new Error('기준표는 10MB 이하로 가져오세요.');setPaste(await file.text());setError('');setMessage('파일을 읽었습니다. 형식·출처를 확인하고 기준표 추가를 누르세요.');}catch(e){setError((e as Error).message);}finally{input.value='';}}}/></label>
      <textarea rows={4} maxLength={MAX_REFERENCE_BYTES} aria-label="Excel 인정 기준표" value={paste} onChange={e=>setPaste(e.target.value)} placeholder={'학술지명\tISSN\teISSN\t구분'}/><Button onClick={addReference}>기준표 추가·선택</Button><p>추가한 기준표는 이 프리셋에만 저장되며 공개 저장소로 전송하지 않습니다. 전체 목록은 <a href="https://mjl.clarivate.com/collection-list-downloads" target="_blank" rel="noopener noreferrer">Clarivate 공식 다운로드 ↗</a>에서 구독 권한으로 받으세요. Excel 파일은 셀을 복사하거나 CSV로 저장해 가져올 수 있습니다.</p>
    </details>
    {error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status" className="notice">{message}</p>}<p className="field-hint">선택한 자료와 추가 기준표는 양식·프리셋에 함께 저장할 수 있습니다. 목록에 없거나 자료가 없는 논문을 자동으로 비인정 처리하지 않습니다.</p>
  </DialogContent></Dialog></>;
}
