'use client';
import { useEffect, useRef, useState, useSyncExternalStore } from 'react';
import { ArrowDown, ArrowUp, Plus, Settings2, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { columnValue, defaultLayout, deleteLocalLayout, displayValue, formats, headersFromTsv, layoutSchema, newColumn, readLocalLayouts, saveLocalLayout, sources, type Column, type Layout, type SortRule } from '@/lib/layouts';
import { googleUser, googleConnection, subscribeGoogle, readGoogleLayouts, saveGoogleLayout, deleteGoogleLayout, restoreGoogleSession, ensureGoogleStorageReady } from '@/lib/google-store';
import { downloadBlob, headerTextColor } from '@/lib/ledger-export';
import type { Paper } from '@/lib/papers';

export function Choice({ value, onChange, options, label, disabled }: { value: string; onChange: (v:string) => void; options: { key:string; label:string }[]; label:string; disabled?:boolean }) { return <Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o => <SelectItem key={o.key} value={o.key}>{o.label}</SelectItem>)}</SelectContent></Select>; }
export function SortControls({ layout, onChange }: { layout: Layout; onChange: (v:Layout) => void }) {
  const options = [...sources.filter(s => !['rowNumber','manual','constant'].includes(s.key)), ...layout.columns.filter(c => c.source !== 'rowNumber').map(c => ({ key:'column:'+c.id, label:'양식 · '+c.label }))];
  function change(i: number, value: Partial<SortRule>) { onChange({ ...layout, sort: layout.sort.map((s,j) => i===j ? {...s,...value} : s) }); }
  return <div className="sort-controls"><strong>정렬</strong>{layout.sort.map((rule,i) => <div className="sort-rule" key={i}><span>{i+1}순위</span><Choice label={`${i+1}순위 정렬 항목`} value={rule.key} options={options} onChange={key => change(i,{key})}/><Choice label={`${i+1}순위 정렬 방향`} value={rule.direction} options={[{key:'asc',label:'오름차순 ↑'},{key:'desc',label:'내림차순 ↓'}]} onChange={direction => change(i,{direction:direction as SortRule['direction']})}/><Button variant="ghost" size="icon" aria-label={`${i+1}순위 정렬 삭제`} onClick={() => onChange({...layout,sort:layout.sort.filter((_,j) => i!==j)})}><Trash2 size={14}/></Button></div>)}{layout.sort.length < 3 && <Button variant="outline" size="sm" onClick={() => onChange({...layout,sort:[...layout.sort,{key:'title',direction:'asc'}]})}><Plus size={14}/>기준 추가</Button>}<small>빈 값은 마지막 · 현재 불러온 행에 적용</small></div>;
}
export function LayoutSettings({ layout, onChange, sample, onMessage }: { layout:Layout; onChange:(v:Layout)=>void; sample?:Paper; onMessage:(s:string)=>void }) {
  const [open,setOpen] = useState(false); const [draft,setDraft] = useState(layout); const [saved,setSaved] = useState<Layout[]>([]);
  const [paste,setPaste] = useState(''); const [orientation,setOrientation] = useState<'row'|'column'>('row'); const [replace,setReplace] = useState(false);
  const [busy,setBusy] = useState(false); const [error,setError] = useState(''); const [message,setMessage] = useState(''); const [deleting,setDeleting] = useState('');
  const user = useSyncExternalStore(subscribeGoogle,googleUser,()=>null); const generation = useRef(0); const importRef = useRef<HTMLInputElement>(null);
  const connection = useSyncExternalStore(subscribeGoogle,googleConnection,()=> 'disconnected');
  useEffect(() => { const seq = ++generation.current; setSaved([]); if (!open) return; setBusy(true); setError(''); restoreGoogleSession().then(() => { ensureGoogleStorageReady(); return googleUser() ? readGoogleLayouts() : readLocalLayouts(); }).then(v => { if(seq===generation.current) setSaved(v); }).catch(e => { if(seq===generation.current) setError('프리셋을 불러오지 못했습니다: '+e.message); }).finally(()=>{if(seq===generation.current) setBusy(false);}); return ()=>{++generation.current;}; },[open,user?.sub,connection]);
  function editColumn(id:string, patch:Partial<Column>) { setDraft(d=>({...d,columns:d.columns.map(c=>c.id===id?{...c,...patch}:c)})); }
  function removeColumn(id:string) { setDraft(d=>({...d,columns:d.columns.filter(c=>c.id!==id),sort:d.sort.filter(s=>s.key!=='column:'+id)})); }
  function move(i:number, direction:number) { setDraft(d=>{const columns=[...d.columns]; [columns[i],columns[i+direction]]=[columns[i+direction],columns[i]]; return {...d,columns};}); }
  function validate():Layout|null { const parsed = layoutSchema.safeParse(draft); if(!parsed.success) {setError('항목 이름·매칭·너비(8~100)·글자 크기(9~20)를 확인하세요. 열은 1~100개입니다.');return null;} setError('');return parsed.data; }
  function apply() { const valid=validate(); if(valid) {onChange(valid);onMessage(valid.name+' 양식을 적용했습니다. 저장 버튼으로 프리셋을 보관할 수 있습니다.');setOpen(false);} }
  async function save(copy:boolean) { const valid=validate(); if(!valid) return; const value={...valid,id:copy||valid.id==='default-17'?crypto.randomUUID():valid.id}; const seq=generation.current; setBusy(true);setMessage('');try {ensureGoogleStorageReady();if(googleUser()) await saveGoogleLayout(value); else saveLocalLayout(value); if(seq!==generation.current)return;setSaved(prev=>[value,...prev.filter(p=>p.id!==value.id)]);setDraft(value);onChange(value);setMessage('프리셋과 정렬 기준을 저장하고 적용했습니다.');}catch(e){if(seq===generation.current)setError((e as Error).message);}finally{if(seq===generation.current)setBusy(false);} }
  async function remove(id:string) { const seq=generation.current;setBusy(true);try{ensureGoogleStorageReady();if(googleUser())await deleteGoogleLayout(id);else deleteLocalLayout(id);if(seq===generation.current){setSaved(prev=>prev.filter(p=>p.id!==id));setDeleting('');}}catch(e){if(seq===generation.current)setError((e as Error).message);}finally{if(seq===generation.current)setBusy(false);} }
  function importHeaders() {try{const columns=headersFromTsv(paste,orientation);if(!replace&&draft.columns.length+columns.length>100)throw new Error('최대 100개 항목입니다. 기존 열 교체를 선택하거나 열 수를 줄이세요.');setDraft(d=>({...d,columns:replace?columns:[...d.columns,...columns],sort:replace?d.sort.filter(s=>!s.key.startsWith('column:')):d.sort}));setMessage(`${columns.length}개 열을 가져왔습니다. 자동 연결을 확인하세요. 미매칭은 논문별 사용자 항목입니다.`);setError('');}catch(e){setError((e as Error).message);} }
  async function importPreset(file?:File) { if(!file)return;try{if(file.size>1000000)throw new Error('프리셋 파일은 1MB 이하여야 합니다.');const parsed=layoutSchema.parse(JSON.parse(await file.text()));setDraft({...parsed,id:crypto.randomUUID()});setMessage('프리셋을 가져왔습니다. 적용하거나 저장하세요.');setError('');}catch{setError('올바른 논문대장 프리셋 JSON 파일인지 확인하세요.');}if(importRef.current)importRef.current.value=''; }
  return <><Button variant="outline" onClick={()=>{setDraft(structuredClone(layout));setOpen(true);setError('');setMessage('');setDeleting('');}}><Settings2 size={16}/>양식·프리셋</Button><Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v);}}><DialogContent className="layout-dialog"><DialogHeader><DialogTitle>내 연구실적 양식 만들기</DialogTitle><DialogDescription>Excel 머리글을 가져오고 각 열을 논문 정보에 연결하세요. 글자 크기·정렬·열 너비·머리글 색은 XLSX에 반영됩니다.</DialogDescription></DialogHeader>
    <div className="preset-storage"><strong>{connection==='restoring' ? 'Google 연결 복원 중…' : connection==='expired' ? 'Google 재연결 필요' : user ? user.email+' · Google 저장소' : '이 브라우저에 저장'}</strong><small>{user?'같은 탭의 새로고침 후에도 연결됩니다. 인증 만료 후에는 다시 연결하세요.':'Google 계정을 연결하면 해당 계정에 저장하고 다른 기기에서도 불러올 수 있습니다.'}</small></div>
    <div className="preset-actions"><Button variant="outline" disabled={busy} onClick={()=>setDraft(defaultLayout())}>기본 17항목 불러오기</Button><Button variant="outline" disabled={busy} onClick={()=>importRef.current?.click()}>프리셋 JSON 가져오기</Button><input type="file" accept="application/json,.json" ref={importRef} className="sr-only" aria-label="프리셋 파일" onChange={e=>void importPreset(e.target.files?.[0])}/><Button variant="outline" disabled={busy} onClick={()=>{const valid=validate();if(valid)downloadBlob(JSON.stringify(valid,null,2),'논문대장_프리셋.json','application/json');}}>프리셋 JSON 내보내기</Button></div>
    {saved.length>0&&<div className="saved-presets">{saved.map(p=><div key={p.id}><Button variant="ghost" disabled={busy} onClick={()=>{setDraft(structuredClone(p));setMessage('저장된 프리셋을 불러왔습니다. 적용을 눌러 반영하세요.');}}>{p.name} <small>{p.columns.length}열</small></Button>{deleting===p.id?<><Button variant="destructive" size="sm" disabled={busy} onClick={()=>void remove(p.id)}>삭제 확인</Button><Button variant="ghost" size="sm" onClick={()=>setDeleting('')}>취소</Button></>:<Button variant="ghost" size="icon" disabled={busy} aria-label={p.name+' 프리셋 삭제'} onClick={()=>setDeleting(p.id)}><Trash2 size={14}/></Button>}</div>)}</div>}
    <label>프리셋 이름<Input value={draft.name} maxLength={80} onChange={e=>setDraft({...draft,name:e.target.value})}/></label>
    <details className="header-import"><summary>Excel에서 머리글 붙여넣기</summary><p>머리글 셀을 복사(Ctrl+C)한 뒤 붙여넣으세요. 가로는 첫 행, 세로는 첫 열을 읽습니다. 빈 셀은 건너뛰고 줄바꿈이 있는 머리글도 보존합니다.</p><textarea aria-label="Excel 머리글 붙여넣기" rows={3} value={paste} onChange={e=>setPaste(e.target.value)} placeholder={'참여교수\t논문명\t출판년월\t학술지명'}/><div className="preset-actions"><Choice label="머리글 방향" value={orientation} onChange={v=>setOrientation(v as 'row'|'column')} options={[{key:'row',label:'가로 첫 행'},{key:'column',label:'세로 첫 열'}]}/><label className="inline-check"><Checkbox checked={replace} onCheckedChange={v=>setReplace(v===true)}/>기존 열을 교체</label><Button onClick={importHeaders} disabled={!paste.trim()}>머리글 가져오기</Button></div></details>
    <div className="layout-columns"><Table><TableHeader><TableRow><TableHead>순서</TableHead><TableHead>열 이름</TableHead><TableHead>연결할 정보</TableHead><TableHead>표시 형식</TableHead><TableHead>정렬</TableHead><TableHead>너비</TableHead><TableHead>삭제</TableHead></TableRow></TableHeader><TableBody>{draft.columns.map((c,i)=><TableRow key={c.id}><TableCell><div className="column-move"><span>{i+1}</span><Button variant="ghost" size="icon" disabled={!i} aria-label={c.label+' 위로'} onClick={()=>move(i,-1)}><ArrowUp size={13}/></Button><Button variant="ghost" size="icon" disabled={i===draft.columns.length-1} aria-label={c.label+' 아래로'} onClick={()=>move(i,1)}><ArrowDown size={13}/></Button></div></TableCell><TableCell><Input value={c.label} maxLength={150} aria-label={`${i+1}번째 열 이름`} onChange={e=>editColumn(c.id,{label:e.target.value})}/></TableCell><TableCell><Choice value={c.source} label={c.label+' 데이터 연결'} onChange={source=>{editColumn(c.id,{source});if(source==='rowNumber')setDraft(d=>({...d,sort:d.sort.filter(s=>s.key!=='column:'+c.id)}));}} options={sources}/>{c.source==='constant'&&<Input className="constant-input" value={c.constant} maxLength={2000} aria-label={c.label+' 고정값'} placeholder="모든 논문에 넣을 값" onChange={e=>editColumn(c.id,{constant:e.target.value})}/>}</TableCell><TableCell><Choice value={c.format} label={c.label+' 형식'} onChange={format=>editColumn(c.id,{format:format as Column['format']})} options={Object.entries(formats).map(([key,label])=>({key,label}))}/></TableCell><TableCell><Choice value={c.align} label={c.label+' 정렬'} onChange={align=>editColumn(c.id,{align:align as Column['align']})} options={[{key:'left',label:'왼쪽'},{key:'center',label:'가운데'},{key:'right',label:'오른쪽'}]}/></TableCell><TableCell><Input type="number" min={8} max={100} value={c.width} aria-label={c.label+' 열 너비'} onChange={e=>editColumn(c.id,{width:Number(e.target.value)})}/></TableCell><TableCell><Button variant="ghost" size="icon" aria-label={c.label+' 열 삭제'} disabled={draft.columns.length<=1} onClick={()=>removeColumn(c.id)}><Trash2 size={14}/></Button></TableCell></TableRow>)}</TableBody></Table></div>
    <Button variant="outline" disabled={draft.columns.length>=100} onClick={()=>setDraft({...draft,columns:[...draft.columns,newColumn()]})}><Plus size={16}/>항목 추가</Button>
    <div className="layout-style"><label>머리글 색<Input type="color" value={draft.style.headerColor} onChange={e=>setDraft({...draft,style:{...draft.style,headerColor:e.target.value}})}/></label><label>글자 크기 (pt)<Input type="number" min={9} max={20} value={draft.style.fontSize} onChange={e=>setDraft({...draft,style:{...draft.style,fontSize:Number(e.target.value)}})}/></label><label className="inline-check"><Checkbox checked={draft.style.striped} onCheckedChange={v=>setDraft({...draft,style:{...draft.style,striped:v===true}})}/>교차 행 배경</label><label className="inline-check"><Checkbox checked={draft.style.wrap} onCheckedChange={v=>setDraft({...draft,style:{...draft.style,wrap:v===true}})}/>셀 줄바꿈</label></div>
    <SortControls layout={draft} onChange={setDraft}/><div className="layout-preview"><strong>양식 미리보기 {sample?'· 첫 논문':'· 데이터를 불러오면 값도 표시됩니다'}</strong><Table style={{fontSize:draft.style.fontSize+'pt'}}><TableHeader><TableRow>{draft.columns.map(c=><TableHead key={c.id} style={{background:draft.style.headerColor,color:headerTextColor(draft.style.headerColor),minWidth:c.width+'ch',textAlign:c.align,whiteSpace:'normal'}}>{c.label}</TableHead>)}</TableRow></TableHeader><TableBody><TableRow>{draft.columns.map(c=><TableCell key={c.id} style={{textAlign:c.align,whiteSpace:draft.style.wrap?'pre-wrap':'nowrap'}}>{sample?displayValue(columnValue(sample,c),c.format)||'—':c.source==='constant'?c.constant:'—'}</TableCell>)}</TableRow></TableBody></Table></div>
    {error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status" className="notice">{message}</p>}<div className="preset-footer"><small>프리셋은 열·서식·정렬을 저장합니다. 논문별 입력값은 Excel/CSV로 보관하세요.</small><div><Button variant="outline" disabled={busy} onClick={()=>void save(true)}>새 프리셋으로 저장</Button><Button variant="outline" disabled={busy} onClick={()=>void save(false)}>{busy?'저장소 연결 중…':'프리셋 저장·적용'}</Button><Button disabled={busy} onClick={apply}>저장 없이 적용</Button></div></div>
  </DialogContent></Dialog></>;
}
